using Microsoft.AspNetCore.Authentication;

namespace CraftersCloud.ReferenceArchitecture.Infrastructure.Api.Security.DummyAuthentication;

public class DummyAuthenticationOptions : AuthenticationSchemeOptions;